controller_list:
  - name: "hand/palm_controller"
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
     - r_wirst_j
     - r_upper_wirst_j

  - name: "hand/finger/thumb_controller"
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
     - r_knuckle_bottom_thumb_j
     - r_knuckle_upper_thumb_j
     - r_middle_thumb_j

  - name: "hand/finger/index_controller"
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
     - r_knuckle_bottom_index_j
     - r_middle_index_j
     - r_top_index_j

  - name: "hand/finger/middle_controller"
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
     - r_knuckle_bottom_middle_j
     - r_middle_middle_j
     - r_top_middle_j

  - name: "hand/finger/third_controller"
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
     - r_knuckle_bottom_third_j
     - r_middle_third_j
     - r_top_third_j

  - name: "hand/finger/little_controller"
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
     - r_knuckle_bottom_little_j
     - r_middle_little_j
     - r_top_little_j

