<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

<xacro:include filename="$(find signbot_f_description)/urdf/signbot.gazebo" />
<xacro:include filename="$(find signbot_f_description)/urdf/materials.xacro" />

<!-- ******************************************************************************************** -->
<!-- **************************************** Constants ***************************************** -->
<!-- ******************************************************************************************** -->
  <property name="PI" value="3.14159"/>
  <property name="TOLERANCE" value="0.001" />
  <property name="HEAVYWEIGHT" value="50" />
  <property name="LIGHTWEIGHT" value="1" />
<!-- Legs Constants -->
  <property name="LEG_DEPTH" value=".20" />
  <property name="LEG_LENGTH" value=".39"/>
  <property name="LEG_HEIGHT" value=".70"/>
<!-- Torso Constants -->
  <property name="TORSO_DEPTH" value=".20" />
  <property name="TORSO_LENGTH" value=".39"/>
  <property name="TORSO_HEIGHT" value=".50"/>
<!-- Neck constants -->
  <property name="NECK_RADIUS" value="0.05" />
  <property name="NECK_LENGTH" value="0.1"/>
<!-- head constants -->
  <property name="HEAD_RADIUS" value="0.15"/>
<!-- arm link properties -->
  <property name="SHOULDER_LENGTH" value="0.001" />
  <property name="ARM_RADIUS" value="0.05" />
  <property name="ARM_LENGTH" value="${0.20-(ELBOW_RADIUS/2)}" />
  <property name="ELBOW_RADIUS" value="0.03" />
  <property name="ELBOW_LENGTH" value="${2*ARM_RADIUS}" />
  <property name="FOREARM_LENGTH" value="${0.29-(ELBOW_RADIUS/2)}" />
<!-- wrist link properties -->
  <property name="WRIST_RADIUS" value="${ARM_RADIUS}" />
  <property name="WRIST_LENGTH" value="0.01" />
<!-- palm link properties -->
  <property name="PALM_DEPTH" value="0.04" />
  <property name="PALM_LENGTH" value="0.09"/>
  <property name="PALM_HEIGHT" value="0.09"/>
<!-- generic fingers properties -->
  <property name="GENERIC_FINGERS_RADIUS" value="0.01" />
  <property name="GENERIC_FINGERS_X" value="0.01" />
  <property name="INTERVAL_BETWEEN_FINGERS" value="0.003" />
  <property name="GENERIC_FINGER_KNUCKLE_RADIUS" value="0.007" />
<!-- thumb finger properties -->
  <property name="THUMB_BOTTOM_LENGTH" value="0.03" />
  <property name="THUMB_TOP_LENGTH" value="${GENERIC_FINGERS_RADIUS}" />
<!-- index finger properties -->
  <property name="INDEX_BOTTOM_LENGTH" value="0.03" />
  <property name="INDEX_MIDDLE_LENGTH" value="0.02" />
  <property name="INDEX_TOP_LENGTH" value="${GENERIC_FINGERS_RADIUS}" />
<!--  middle finger properties  -->
  <property name="MIDDLE_BOTTOM_LENGTH" value="0.04" />
  <property name="MIDDLE_MIDDLE_LENGTH" value="0.03" />
  <property name="MIDDLE_TOP_LENGTH" value="${GENERIC_FINGERS_RADIUS}" />
<!--  third finger properties  -->
  <property name="THIRD_BOTTOM_LENGTH" value="0.035" />
  <property name="THIRD_MIDDLE_LENGTH" value="0.02" />
  <property name="THIRD_TOP_LENGTH" value="${GENERIC_FINGERS_RADIUS}" />
<!--  little finger properties  -->
  <property name="LITTLE_BOTTOM_LENGTH" value="0.02" />
  <property name="LITTLE_MIDDLE_LENGTH" value="0.01" />
  <property name="LITTLE_TOP_LENGTH" value="${GENERIC_FINGERS_RADIUS}" />

<!-- ******************************************************************************************** -->
<!-- ***************************/ Blocks of code ************************************************ -->
<!-- ******************************************************************************************** -->
<xacro:macro name="inertial_matrix" params="mass">
  <inertial>
    <mass value="${mass}" />
    <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="0.5" iyz="0.0" izz="1.0" />
  </inertial>
</xacro:macro>

<xacro:macro name="transmission_block" params="joint_name">
  <transmission name="tran1">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="${joint_name}">
      <hardwareInterface>PositionJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor1">
      <hardwareInterface>PositionJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>
</xacro:macro>
<!-- ****************************** LINK SHAPES	************************************************* -->
<xacro:macro name="link_shape" params="name color *origin *shape mass">
  <link name="${name}">
    <visual>
       <xacro:insert_block name="origin" />
        <geometry>
            <xacro:insert_block name="shape" />
        </geometry>
        <material name="${color}" />
    </visual>
    <collision>
       <xacro:insert_block name="origin" />
        <geometry>
            <xacro:insert_block name="shape" />
        </geometry>
    </collision>
    <xacro:inertial_matrix mass="${mass}"/>
  </link>
</xacro:macro>

<!-- ******************************************************************************************** -->
<!-- ************************************** TORSO_HEAD ****************************************** -->
<!-- ******************************************************************************************** -->
<xacro:macro name="torso_head" params="parentl_name">
  <joint name="ankle_joint" type="fixed">
     <origin xyz="0 0 0" rpy="0 0 0" />
     <parent link="${parentl_name}"/>
     <child link="legs_link"/>
  </joint>

  <xacro:link_shape name="legs_link" color="Black"  mass="${HEAVYWEIGHT}" >
                    <origin xyz="0 0 ${LEG_HEIGHT/2}" rpy="0 0 0" />
                    <box size="${LEG_DEPTH} ${LEG_LENGTH} ${LEG_HEIGHT}" />
  </xacro:link_shape>
  <xacro:gazebo_black name="legs_link" />
  <!-- ************************************ TORSO LINK ****************************************** -->
  <joint name="waist_joint" type="fixed">
    <origin xyz="0 0 ${LEG_HEIGHT}" rpy="0 0 0" />
    <parent link="legs_link"/>
    <child link="torso_link"/>
  </joint>

  <xacro:link_shape name="torso_link" color="White" mass="${LIGHTWEIGHT}" >
        <origin xyz="0 0 ${TORSO_HEIGHT/2}" rpy="0 0 0" />
        <box size="${TORSO_DEPTH} ${TORSO_LENGTH} ${TORSO_HEIGHT}" />
  </xacro:link_shape>
  <xacro:gazebo_white name="torso_link" />
  <!-- ************************************** NECK LINK ***************************************** -->
  <joint name="neck_joint" type="fixed">
    <origin xyz="0 0 ${TORSO_HEIGHT}" rpy="0 0 0" />
    <parent link="torso_link"/>
    <child link="neck_link"/>
  </joint>

  <xacro:link_shape name="neck_link" color="White" mass="${LIGHTWEIGHT}">
        <origin xyz="0 0 ${NECK_LENGTH/2}" rpy="0 0 0" />
        <cylinder radius="${NECK_RADIUS}" length="${NECK_LENGTH}"/>
  </xacro:link_shape>
  <xacro:gazebo_white name="neck_link" />
  <!-- ************************************* HEAD LINK ****************************************** -->
  <joint name="head_joint" type="fixed">
     <origin xyz="0 0 ${NECK_LENGTH}" rpy="0 0 0" />
     <parent link="neck_link"/>
     <child link="head_link"/>
  </joint>

  <xacro:link_shape name="head_link" color="White" mass="${LIGHTWEIGHT}">
        <origin xyz="0 0 ${HEAD_RADIUS}" rpy="0 0 0" />
        <sphere radius="${HEAD_RADIUS}"/>
  </xacro:link_shape>
  <xacro:gazebo_white name="head_link" />

</xacro:macro>

<!-- ******************************************************************************************** -->
<!-- ****************************************** ARMS ******************************************** -->
<!-- ******************************************************************************************** -->
<xacro:macro name="arm" params="side axis_y_signal lower upper" >
<!-- ********************************* SHOULDER1 LINK ******************************************* -->
  <xacro:link_shape name="${side}_shoulder1_link" color="Blue" mass="${LIGHTWEIGHT}">
        <origin xyz="0 0 0" rpy="${PI/2} 0 0" />
         <cylinder radius="${ARM_RADIUS}" length="${SHOULDER_LENGTH}"/>
  </xacro:link_shape>
  <xacro:gazebo_blue name="${side}_shoulder1_link" />

  <joint name="${side}_shoulder1_joint" type="revolute">
    <parent link="torso_link"/>
    <child link="${side}_shoulder1_link"/>
    <origin xyz="0 ${axis_y_signal*((TORSO_LENGTH/2)+(SHOULDER_LENGTH/2))} ${TORSO_HEIGHT-ARM_RADIUS}"/>
    <axis xyz="0 1 0"/>
    <limit effort="1000.0" lower="0" upper="${PI/2}" velocity="0.5"/>
    <dynamics damping="50" friction="1"/>
  </joint>
<!-- ********************************* SHOULDER2 LINK **************************************** -->
  <xacro:link_shape name="${side}_shoulder2_link" color="Blue" mass="${LIGHTWEIGHT}">
        <origin xyz="0 0 0" rpy="0 0 0" />
        <sphere radius="${ARM_RADIUS}"/>
  </xacro:link_shape>
  <xacro:gazebo_blue name="${side}_shoulder2_link" />

  <joint name="${side}_shoulder2_joint" type="revolute">
    <parent link="${side}_shoulder1_link"/>
    <child link="${side}_shoulder2_link"/>
    <origin xyz="0 ${axis_y_signal*((SHOULDER_LENGTH/2)+ARM_RADIUS)} 0"/>
    <axis xyz="0 0 1"/>
    <limit effort="1000.0" lower="${lower*(-1*(PI/2))}" upper="${upper*(PI/2)}" velocity="0.5"/>
    <dynamics damping="50" friction="1"/>
  </joint>
<!-- ****************************************** ARM ****************************************** -->
  <xacro:link_shape name="${side}_arm_link" color="White" mass="${LIGHTWEIGHT}">
        <origin rpy="${PI/2} 0 0" xyz="0 ${axis_y_signal*(ARM_LENGTH/2)} 0"/>
        <cylinder radius="${ARM_RADIUS}" length="${ARM_LENGTH}"/>
  </xacro:link_shape>
  <xacro:gazebo_white name="${side}_arm_link" />

  <joint name="${side}_arm_joint" type="revolute">
    <parent link="${side}_shoulder2_link"/>
    <child link="${side}_arm_link"/>
    <origin xyz="0 0 0"/>
    <axis xyz="1 0 0"/>
    <limit effort="1000.0" lower="${(-1)*(PI/2)}" upper="${(PI/2)}" velocity="0.5"/>
    <dynamics damping="50" friction="1"/>
  </joint>
<!-- ****************************************** ELBOW ****************************************** -->
  <xacro:link_shape name="${side}_elbow_link" color="Blue" mass="${LIGHTWEIGHT}">
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <cylinder radius="${ELBOW_RADIUS}" length="${ELBOW_LENGTH}"/>
  </xacro:link_shape>
  <xacro:gazebo_blue name="${side}_elbow_link" />

  <joint name="${side}_elbow1_joint" type="revolute">
    <parent link="${side}_arm_link"/>
    <child link="${side}_elbow_link"/>
    <origin xyz="0 ${axis_y_signal*(ARM_LENGTH+ELBOW_RADIUS)} 0"/>
    <axis xyz="0 0 1"/>
    <limit effort="1000.0" lower="${lower*-1*(PI/2)}" upper="${upper*(PI/2)}" velocity="0.5"/>
    <dynamics damping="50" friction="1"/>
  </joint>
<!-- ****************************************** FOREARM **************************************** -->
  <xacro:link_shape name="${side}_forearm_link" color="White" mass="${LIGHTWEIGHT}">
         <origin rpy="${PI/2} 0 0" xyz="0 ${axis_y_signal*(FOREARM_LENGTH/2)} 0"/>
         <cylinder radius="${ARM_RADIUS}" length="${FOREARM_LENGTH}"/>
  </xacro:link_shape>
  <xacro:gazebo_white name="${side}_forearm_link" />

  <joint name="${side}_elbow2_joint" type="fixed">
    <parent link="${side}_elbow_link"/>
    <child link="${side}_forearm_link"/>
    <origin xyz="0 ${axis_y_signal*(ELBOW_RADIUS)} 0"/>
  </joint>
<!-- ************************************** TRANSMICION ROS CONTROL **************************** -->
          <xacro:transmission_block joint_name="${side}_shoulder1_joint"/>
          <xacro:transmission_block joint_name="${side}_shoulder2_joint"/>
          <xacro:transmission_block joint_name="${side}_arm_joint"/>
          <xacro:transmission_block joint_name="${side}_elbow1_joint"/>

</xacro:macro>

<!-- ******************************************************************************************** -->
<!-- ****************************************** PALM ******************************************** -->
<!-- ******************************************************************************************** -->
<xacro:macro name="palm" params="side axis_y_signal">
<!-- ***************************************** WIRST1 ******************************************* -->
  <xacro:link_shape name="${side}_wirst1_l" color="Blue" mass="${LIGHTWEIGHT}">
        <origin xyz="0 0 0" rpy="${PI/2} 0 0" />
        <cylinder radius="${WRIST_RADIUS}" length="${WRIST_LENGTH}"/>
  </xacro:link_shape>
  <xacro:gazebo_blue name="${side}_wirst1_l" />

  <joint name="${side}_wirst1_j" type="revolute">
    <parent link="${side}_forearm_link"/>
    <child link="${side}_wirst1_l"/>
    <origin xyz="0 ${axis_y_signal*(FOREARM_LENGTH+(WRIST_LENGTH/2))} 0"/>
    <axis xyz="0 1 0"/>
    <limit effort="1000.0" lower="0" upper="${PI/2}" velocity="0.5"/>
    <dynamics damping="50" friction="1"/>
  </joint>
<!-- ***************************************** WIRST2 ******************************************* -->
  <xacro:link_shape name="${side}_wirst2_l" color="Blue" mass="${LIGHTWEIGHT}">
        <origin xyz="0 0 0" rpy="0 0 0" />
        <sphere radius="${WRIST_RADIUS}"/>
  </xacro:link_shape>
  <xacro:gazebo_blue name="${side}_wirst2_l" />

  <joint name="${side}_wirst2_j" type="revolute">
    <parent link="${side}_wirst1_l"/>
    <child link="${side}_wirst2_l"/>
    <origin xyz="0 ${axis_y_signal*(WRIST_LENGTH/2)} 0"/>
    <axis xyz="1 0 0"/>
    <limit effort="1000.0" lower="-${PI/4}" upper="${PI/4}" velocity="0.5"/>
    <dynamics damping="50" friction="1"/>
  </joint>
<!-- ****************************************** PALM LINK *************************************** -->
  <xacro:link_shape name="${side}_palm_l" color="White" mass="${LIGHTWEIGHT}">
        <origin rpy="${PI/2} 0 0" xyz="0 ${axis_y_signal*PALM_LENGTH/2} 0 "/>
        <box size="${PALM_DEPTH} ${PALM_LENGTH} ${PALM_HEIGHT}"/>
  </xacro:link_shape>
  <xacro:gazebo_white name="${side}_palm_l" />

  <joint name="${side}_wirst3_j" type="revolute">
    <parent link="${side}_wirst2_l"/>
    <child link="${side}_palm_l"/>
    <origin xyz="0 ${axis_y_signal*WRIST_RADIUS} 0"/>
    <axis xyz="0 0 1"/>
    <limit effort="1000.0" lower="-${PI/4}" upper="${PI/4}" velocity="0.5"/>
    <dynamics damping="50" friction="1"/>
  </joint>
<!--************************************** TRANSMICION ROS CONTROL ****************************** -->
   <xacro:transmission_block joint_name="${side}_wirst1_j"/>
   <xacro:transmission_block joint_name="${side}_wirst2_j"/>
   <xacro:transmission_block joint_name="${side}_wirst3_j"/>

</xacro:macro>

<!-- ******************************************************************************************** -->
<!-- ********************************** THUMB FINGER ******************************************** -->
<!-- ******************************************************************************************** -->
<!-- ****************************** BOT KNICKLE ************************************************* -->
<xacro:macro name="thumb_finger" params="side axis_y_signal lower upper ">
    <xacro:link_shape name="${side}_bottom_knuckle_thumb_l" color="Blue" mass="${LIGHTWEIGHT}">
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <sphere radius="${GENERIC_FINGERS_RADIUS}" />
    </xacro:link_shape>
    <xacro:gazebo_blue name="${side}_bottom_knuckle_thumb_l" />

    <joint name="${side}_bottom_knuckle1_thumb_j" type="revolute">
        <parent link="${side}_palm_l"/>
        <child link="${side}_bottom_knuckle_thumb_l"/>
        <origin xyz="0 ${axis_y_signal*GENERIC_FINGERS_RADIUS} ${(PALM_LENGTH/2)+GENERIC_FINGERS_RADIUS+TOLERANCE}" />
        <axis xyz="1 0 0"/>
        <limit effort="1000.0" lower="-${lower*(PI/2)}" upper="${upper*(PI/2)}" velocity="0.5"/>
        <dynamics damping="50" friction="1"/>
    </joint>
<!-- ********************************** BOT THUMB ********************************************** -->
    <xacro:link_shape name="${side}_bottom_thumb_l" color="White" mass="${LIGHTWEIGHT}">
        <origin rpy="0 0 0" xyz="0 0 ${THUMB_BOTTOM_LENGTH/2}"/>
        <cylinder radius="${GENERIC_FINGERS_RADIUS}" length="${THUMB_BOTTOM_LENGTH}"/>
    </xacro:link_shape>
    <xacro:gazebo_white name="${side}_bottom_thumb_l" />

    <joint name="${side}_bottom_knuckle2_thumb_j" type="revolute">
        <parent link="${side}_bottom_knuckle_thumb_l"/>
        <child link="${side}_bottom_thumb_l"/>
        <origin xyz="0 0 0"/>
        <axis xyz="0 1 0"/>
        <limit effort="1000.0" lower="0" upper="${PI/2}" velocity="0.5"/>
        <dynamics damping="50" friction="1"/>
    </joint>
<!-- *********************************** MIDDLE KNUCKLE ****************************************** -->
      <xacro:link_shape name="${side}_middle_knuckle_thumb_l" color="Blue" mass="${LIGHTWEIGHT}" >
          <origin rpy="0 ${PI/2} 0" xyz="0 0 0"/>
          <cylinder radius="${GENERIC_FINGER_KNUCKLE_RADIUS}" length="${GENERIC_FINGERS_RADIUS*2}"/>
      </xacro:link_shape>
      <xacro:gazebo_blue name="${side}_middle_knuckle_thumb_l" />

      <joint name="${side}_top_knuckle_thumb_j" type="revolute">
          <parent link="${side}_bottom_thumb_l"/>
          <child link="${side}_middle_knuckle_thumb_l"/>
          <origin xyz="0 0 ${THUMB_BOTTOM_LENGTH+GENERIC_FINGER_KNUCKLE_RADIUS}"/>
          <axis xyz="1 0 0"/>
          <limit effort="1000.0" lower="-${lower*(PI/2)}" upper="${upper*(PI/2)}" velocity="0.5"/>
          <dynamics damping="50" friction="1"/>
      </joint>
<!-- ************************************ MIDDLE THUMB ****************************************** -->
    <xacro:link_shape name="${side}_middle_thumb_l" color="White" mass="${LIGHTWEIGHT}" >
        <origin rpy="0 0 0" xyz="0 0 ${THUMB_TOP_LENGTH/2}"/>
        <cylinder radius="${GENERIC_FINGERS_RADIUS}" length="${THUMB_TOP_LENGTH}"/>
    </xacro:link_shape>
    <xacro:gazebo_white name="${side}_middle_thumb_l" />

    <joint name="${side}_middle_thumb_j" type="fixed">
        <parent link="${side}_middle_knuckle_thumb_l"/>
        <child link="${side}_middle_thumb_l"/>
        <origin xyz="0 0 ${GENERIC_FINGER_KNUCKLE_RADIUS}"/>
    </joint>
<!-- ************************************ TOP THUMB ******************************************** -->
    <xacro:link_shape name="${side}_top_thumb_l" color="White" mass="${LIGHTWEIGHT}">
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <sphere radius="${GENERIC_FINGERS_RADIUS}"/>
    </xacro:link_shape>
    <xacro:gazebo_white name="${side}_top_thumb_l" />

    <joint name="${side}_top_thumb_j" type="fixed">
        <parent link="${side}_middle_thumb_l"/>
        <child link="${side}_top_thumb_l"/>
        <origin xyz="0 0 ${THUMB_TOP_LENGTH}"/>
    </joint>
<!-- ************************************ TRANSMICION ROS CONTROL ******************************* -->
   <xacro:transmission_block joint_name="${side}_bottom_knuckle1_thumb_j"/>
   <xacro:transmission_block joint_name="${side}_bottom_knuckle2_thumb_j"/>
   <xacro:transmission_block joint_name="${side}_top_knuckle_thumb_j"/>

</xacro:macro>

<!-- ********************************************************************************************* -->
<!-- ********************************** GENERIC FINGER	******************************************
      palm -> 0.43 for 4 fingers + 0.01 of interval between fingers
              finger radius: 0.05
              0.05*2*4+3*0.01 = 0.43 -->
<!-- ********************************************************************************************* -->
<xacro:macro name="generic_finger"
        params="name side axis_y_signal lower upper ref_point bottom_length middle_length top_length">
<!-- ***************************************** BOT KNUCKLE *************************************** -->
    <xacro:link_shape name="${side}_bottom_knuckle_${name}_l" color="Blue" mass="${LIGHTWEIGHT}">
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <sphere radius="${GENERIC_FINGERS_RADIUS}" />
    </xacro:link_shape>
    <xacro:gazebo_blue name="${side}_bottom_knuckle_${name}_l" />

    <joint name="${side}_bottom_knuckle_${name}_j" type="revolute">
        <parent link="${side}_palm_l"/>
        <child link="${side}_bottom_knuckle_${name}_l"/>
        <origin xyz="${GENERIC_FINGERS_X} ${axis_y_signal*PALM_HEIGHT} ${ref_point}"/>
        <axis xyz="0 0 1"/>
        <limit effort="1000.0" lower="-${lower*(PI/2)}" upper="${upper*(PI/2)}" velocity="0.5"/>
        <dynamics damping="50" friction="1"/>
    </joint>
<!-- ************************************* BOT FINGER ******************************************** -->
    <xacro:link_shape name="${side}_bottom_${name}_l" color="White" mass="${LIGHTWEIGHT}">
        <origin rpy="${PI/2} 0 0" xyz="0 ${axis_y_signal*(bottom_length/2)} 0"/>
        <cylinder radius="${GENERIC_FINGERS_RADIUS}" length="${bottom_length}"/>
    </xacro:link_shape>
    <xacro:gazebo_white name="${side}_bottom_${name}_l" />

    <joint name="${side}_knuckle_upper_${name}_j" type="fixed">
        <parent link="${side}_bottom_knuckle_${name}_l"/>
        <child link="${side}_bottom_${name}_l"/>
        <origin xyz="0 ${axis_y_signal*GENERIC_FINGERS_RADIUS} 0"/>
    </joint>
<!-- ***************************************** MIDDLE KNUCKLE ************************************** -->
  <xacro:link_shape name="${side}_middle_knuckle_${name}_l" color="Blue" mass="${LIGHTWEIGHT}">
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <cylinder radius="${GENERIC_FINGER_KNUCKLE_RADIUS}" length="${GENERIC_FINGERS_RADIUS*2}"/>
  </xacro:link_shape>
  <xacro:gazebo_blue name="${side}_middle_knuckle_${name}_l" />

  <joint name="${side}_middle_knuckle_${name}_j" type="revolute">
      <parent link="${side}_bottom_${name}_l"/>
      <child link="${side}_middle_knuckle_${name}_l"/>
      <origin xyz="0 ${axis_y_signal*(bottom_length+GENERIC_FINGER_KNUCKLE_RADIUS)} 0"/>
      <axis xyz="0 0 1"/>
  <limit effort="1000.0" lower="-${lower*(PI/2)}" upper="${upper*(PI/2)}" velocity="0.5"/>
  <dynamics damping="50" friction="1"/>
  </joint>
<!-- ***************************************** MIDDLE FINGER ************************************** -->
    <xacro:link_shape name="${side}_middle_${name}_l" color="White" mass="${LIGHTWEIGHT}">
        <origin rpy="${PI/2} 0 0" xyz="0 ${axis_y_signal*(middle_length/2)} 0"/>
        <cylinder radius="${GENERIC_FINGERS_RADIUS}" length="${middle_length}"/>
    </xacro:link_shape>
    <xacro:gazebo_white name="${side}_middle_${name}_l" />

    <joint name="${side}_middle_${name}_j" type="fixed">
        <parent link="${side}_middle_knuckle_${name}_l"/>
        <child link="${side}_middle_${name}_l"/>
        <origin xyz="0 ${axis_y_signal*(GENERIC_FINGER_KNUCKLE_RADIUS)} 0"/>
    </joint>
<!-- ***************************************** TOP KNUCKLE **************************************** -->
    <xacro:link_shape name="${side}_top_knuckle_${name}_l" color="Blue" mass="${LIGHTWEIGHT}">
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <cylinder radius="${GENERIC_FINGER_KNUCKLE_RADIUS}" length="${GENERIC_FINGERS_RADIUS*2}"/>
    </xacro:link_shape>
    <xacro:gazebo_blue name="${side}_top_knuckle_${name}_l" />

    <joint name="${side}_top_knuckle_${name}_j" type="revolute">
        <parent link="${side}_middle_${name}_l"/>
        <child link="${side}_top_knuckle_${name}_l"/>
        <origin xyz="0 ${axis_y_signal*(middle_length+GENERIC_FINGER_KNUCKLE_RADIUS)} 0"/>
        <axis xyz="0 0 1"/>
        <limit effort="1000.0" lower="-${lower*(PI/2)}" upper="${upper*(PI/2)}" velocity="0.5"/>
        <dynamics damping="50" friction="1"/>
    </joint>
<!-- ******************************************** TOP FINGER ************************************** -->
    <xacro:link_shape name="${side}_top_${name}_l" color="White" mass="${LIGHTWEIGHT}">
        <origin rpy="${PI/2} 0 0" xyz="0 ${axis_y_signal*(top_length/2)} 0"/>
        <cylinder radius="${GENERIC_FINGERS_RADIUS}" length="${top_length}"/>
    </xacro:link_shape>
    <xacro:gazebo_white name="${side}_top_${name}_l" />

    <joint name="${side}_top_${name}_j" type="fixed">
        <parent link="${side}_top_knuckle_${name}_l"/>
        <child link="${side}_top_${name}_l"/>
        <origin xyz="0 ${axis_y_signal*GENERIC_FINGER_KNUCKLE_RADIUS} 0"/>
    </joint>
<!-- ****************************************** TOPTOP FINGER ************************************* -->
    <xacro:link_shape name="${side}_toptop_${name}_l" color="White" mass="${LIGHTWEIGHT}">
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <sphere radius="${GENERIC_FINGERS_RADIUS}"/>
    </xacro:link_shape>
    <xacro:gazebo_white name="${side}_toptop_${name}_l" />

    <joint name="${side}_toptop_${name}_j" type="fixed">
        <parent link="${side}_top_${name}_l"/>
        <child link="${side}_toptop_${name}_l"/>
        <origin xyz="0 ${axis_y_signal*GENERIC_FINGERS_RADIUS} 0"/>
    </joint>
<!-- ********************************** TRANSMICION ROS CONTROL *********************************** -->
   <xacro:transmission_block joint_name="${side}_bottom_knuckle_${name}_j"/>
   <xacro:transmission_block joint_name="${side}_middle_knuckle_${name}_j"/>
   <xacro:transmission_block joint_name="${side}_top_knuckle_${name}_j"/>

</xacro:macro>

</robot>
