<?xml version="1.0"?>

<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
<xacro:include filename="$(find signbot_description)/urdf/signbot_generic_macros.xacro" />

<!-- arm link properties -->
  <property name="ARM_RADIUS" value="0.2" />
  <property name="ARM_TOP_LENGTH" value="0.6" />
  <property name="ARM_BOTTOM_LENGTH" value="0.7" />

<!-- 	//////////////////	ARMS		/////////////////// -->
<xacro:macro name="arm" params="side axis_y_signal lower upper">
<!--	/////////////	-->
    
  <!-- SHOULDER PAN LINK -->
  <xacro:link_shape name="${side}_shoulder_link" color="Blue">
	<origin xyz="0 0 0" rpy="0 0 0" />
	<sphere radius="${ARM_RADIUS}"/>
  </xacro:link_shape>

  <gazebo reference="${side}_shoulder_link">
    <material>Gazebo/Blue</material>
  </gazebo>

  <joint name="${side}_shoulder_joint" type="revolute">
    <parent link="torso_link"/>
    <child link="${side}_shoulder_link"/>
    <origin xyz="0 ${axis_y_signal*((TORSO_LENGTH/2)+ARM_RADIUS)} ${TORSO_HEIGHT-ARM_RADIUS}"/>
    <axis xyz="0 1 0"/>
    <limit effort="1000.0" lower="-${PI/2}" upper="${PI/2}" velocity="0.5"/>
    <dynamics damping="50" friction="1"/>
  </joint>

<!-- TOP ARM  -->
  <xacro:link_shape name="${side}_top_arm_link" color="White">
	<origin rpy="${PI/2} 0 0" xyz="0 ${axis_y_signal*(ARM_TOP_LENGTH/2)} 0"/>
	<cylinder radius="${ARM_RADIUS}" length="${ARM_TOP_LENGTH}"/>
  </xacro:link_shape>

  <gazebo reference="${side}_top_arm_link">
    <material>Gazebo/White</material>
  </gazebo>

  <joint name="${side}_top_arm_joint" type="revolute">
    <parent link="${side}_shoulder_link"/>
    <child link="${side}_top_arm_link"/>
    <origin xyz="0 0 0"/>
    <axis xyz="0 0 1"/>
    <limit effort="1000.0" lower="${lower*(-1*(PI/2))}" upper="${upper*(PI/2)}" velocity="0.5"/>
    <dynamics damping="50" friction="1"/>
  </joint>

<!-- bottom arm -->
  <xacro:link_shape name="${side}_bottom_arm_link" color="White">
	 <origin rpy="${PI/2} 0 0" xyz="-${ARM_RADIUS} ${axis_y_signal*(ARM_BOTTOM_LENGTH/2)} 0"/>
	 <cylinder radius="${ARM_RADIUS}" length="${ARM_BOTTOM_LENGTH}"/>
  </xacro:link_shape>

  <gazebo reference="${side}_bottom_arm_link">
    <material>Gazebo/White</material>
  </gazebo>

  <joint name="${side}_elbow_joint" type="revolute">
    <parent link="${side}_top_arm_link"/>
    <child link="${side}_bottom_arm_link"/>
    <origin xyz="${ARM_RADIUS} ${axis_y_signal*(ARM_TOP_LENGTH)} 0"/>
    <axis xyz="0 0 1"/>
    <limit effort="1000.0" lower="${lower*(-1)*(PI-0.4)}" upper="${upper*(PI-0.4)}" velocity="0.5"/>
    <dynamics damping="50" friction="1"/>
  </joint>

<!--///	TRANSMICION ROS CONTROL	/// -->
	<xacro:transmission_block joint_name="${side}_shoulder_joint"/>
	<xacro:transmission_block joint_name="${side}_top_arm_joint"/>
	<xacro:transmission_block joint_name="${side}_elbow_joint"/>
  
</xacro:macro>


<!--	//////////////////////	HANDS	//////////////////////// -->
<xacro:macro name="hand" params="side axis_y_signal">

  <xacro:link_shape name="${side}_hand_link" color="Blue">
	<origin  rpy="0 0 0" xyz="0 ${axis_y_signal*(0.3/2)} 0"/>
	<box size="${ARM_RADIUS} 0.3 ${ARM_RADIUS}"/>
  </xacro:link_shape>

  <gazebo reference="${side}_hand_link">
    <material>Gazebo/Blue</material>
  </gazebo>

  <joint name="${side}_wrist_joint" type="continuous">
    <parent link="${side}_bottom_arm_link"/>
    <child link="${side}_hand_link"/>
    <origin rpy="0 0 0" xyz="-${ARM_RADIUS} ${axis_y_signal*(ARM_BOTTOM_LENGTH)} 0.0"/>
    <axis xyz="0 1 0"/>
    <limit effort="1000.0" velocity="1"/>
    <dynamics damping="50" friction="1"/>
  </joint>

<!--///	TRANSMICION ROS CONTROL	/// -->
	<xacro:transmission_block joint_name="${side}_wrist_joint"/>
  
</xacro:macro>

</robot>
