<?xml version="1.0"?>

<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
<xacro:include filename="$(find signbot_description)/urdf/signbot_generic_macros.xacro" />

<!-- Constants -->
  <property name="TOLERANCE" value="0.001" /> 
<!-- arm link properties -->
  <property name="ARM_RADIUS" value="0.2" />
  <property name="ARM_TOP_LENGTH" value="0.6" />
  <property name="ARM_BOTTOM_LENGTH" value="0.7" />
<!-- wrist link properties -->
  <property name="WRIST_RADIUS" value="${ARM_RADIUS}" />
<!-- palm link properties -->
  <property name="PALM_DEPTH" value="${WRIST_RADIUS}" />
  <property name="PALM_LENGTH" value="0.43"/> 
  <property name="PALM_HEIGHT" value="0.35"/>
<!-- thumb finger properties -->
  <property name="THUMB_RADIUS" value="0.06" />
  <property name="THUMB_BOTTOM_LENGTH" value="0.11" />
  <property name="THUMB_TOP_LENGTH" value="${THUMB_RADIUS}" />
<!-- generic fingers properties -->
  <property name="GENERIC_FINGERS_RADIUS" value="0.05" />
  <property name="GENERIC_FINGERS_X" value="0.027" />
  <property name="INTERVAL_BETWEEN_FINGERS" value="0.01" />
<!-- index finger properties -->
  <property name="INDEX_BOTTOM_LENGTH" value="0.1" />
  <property name="INDEX_MIDDLE_LENGTH" value="0.09" />
  <property name="INDEX_TOP_LENGTH" value="${GENERIC_FINGERS_RADIUS}" />
<!--  middle finger properties  -->
  <property name="MIDDLE_BOTTOM_LENGTH" value="0.12" />
  <property name="MIDDLE_MIDDLE_LENGTH" value="0.11" />
  <property name="MIDDLE_TOP_LENGTH" value="${GENERIC_FINGERS_RADIUS}" />
<!--  third finger properties  -->
  <property name="THIRD_BOTTOM_LENGTH" value="0.1" />
  <property name="THIRD_MIDDLE_LENGTH" value="0.1" />
  <property name="THIRD_TOP_LENGTH" value="${GENERIC_FINGERS_RADIUS}" />
<!--  little finger properties  -->
  <property name="LITTLE_BOTTOM_LENGTH" value="0.075" />
  <property name="LITTLE_MIDDLE_LENGTH" value="0.075" />
  <property name="LITTLE_TOP_LENGTH" value="${GENERIC_FINGERS_RADIUS}" />

<!-- 	//////////////////	ARMS		/////////////////// -->
<xacro:macro name="arm" params="side axis_y_signal lower upper">
<!--	/////////////	-->
    
  <!-- SHOULDER PAN LINK -->
  <xacro:link_shape name="${side}_shoulder_link" color="Blue">
	<origin xyz="0 0 0" rpy="0 0 0" />
	<sphere radius="${ARM_RADIUS}"/>
  </xacro:link_shape>

  <gazebo reference="${side}_shoulder_link">
    <material>Gazebo/Blue</material>
  </gazebo>

  <joint name="${side}_shoulder_joint" type="revolute">
    <parent link="torso_link"/>
    <child link="${side}_shoulder_link"/>
    <origin xyz="0 ${axis_y_signal*((TORSO_LENGTH/2)+ARM_RADIUS)} ${TORSO_HEIGHT-ARM_RADIUS}"/>
    <axis xyz="0 1 0"/>
    <limit effort="1000.0" lower="-${PI/2}" upper="${PI/2}" velocity="0.5"/>
    <dynamics damping="50" friction="1"/>
  </joint>

<!-- TOP ARM  -->
  <xacro:link_shape name="${side}_top_arm_link" color="White">
	<origin rpy="${PI/2} 0 0" xyz="0 ${axis_y_signal*(ARM_TOP_LENGTH/2)} 0"/>
	<cylinder radius="${ARM_RADIUS}" length="${ARM_TOP_LENGTH}"/>
  </xacro:link_shape>

  <gazebo reference="${side}_top_arm_link">
    <material>Gazebo/White</material>
  </gazebo>

  <joint name="${side}_top_arm_joint" type="revolute">
    <parent link="${side}_shoulder_link"/>
    <child link="${side}_top_arm_link"/>
    <origin xyz="0 0 0"/>
    <axis xyz="0 0 1"/>
    <limit effort="1000.0" lower="${lower*(-1*(PI/2))}" upper="${upper*(PI/2)}" velocity="0.5"/>
    <dynamics damping="50" friction="1"/>
  </joint>

<!-- bottom arm -->
  <xacro:link_shape name="${side}_bottom_arm_link" color="White">
	 <origin rpy="${PI/2} 0 0" xyz="-${ARM_RADIUS} ${axis_y_signal*(ARM_BOTTOM_LENGTH/2)} 0"/>
	 <cylinder radius="${ARM_RADIUS}" length="${ARM_BOTTOM_LENGTH}"/>
  </xacro:link_shape>

  <gazebo reference="${side}_bottom_arm_link">
    <material>Gazebo/White</material>
  </gazebo>

  <joint name="${side}_elbow_joint" type="revolute">
    <parent link="${side}_top_arm_link"/>
    <child link="${side}_bottom_arm_link"/>
    <origin xyz="${ARM_RADIUS} ${axis_y_signal*(ARM_TOP_LENGTH)} 0"/>
    <axis xyz="0 0 1"/>
    <limit effort="1000.0" lower="${lower*(-1)*(PI-0.4)}" upper="${upper*(PI-0.4)}" velocity="0.5"/>
    <dynamics damping="50" friction="1"/>
  </joint>

<!--///	TRANSMICION ROS CONTROL	/// -->
	<xacro:transmission_block joint_name="${side}_shoulder_joint"/>
	<xacro:transmission_block joint_name="${side}_top_arm_joint"/>
	<xacro:transmission_block joint_name="${side}_elbow_joint"/>
  
</xacro:macro>

<!--	//////////////////////	HANDS	//////////////////////// -->
<xacro:macro name="hand" params="side axis_y_signal">
<!-- wirst -->
  <xacro:link_shape name="${side}_wirst_l" color="Blue">
	<origin xyz="0 0 0" rpy="0 0 0" />
	<sphere radius="${WRIST_RADIUS}"/>
  </xacro:link_shape>

  <gazebo reference="${side}_wirst_l">
    <material>Gazebo/Blue</material>
  </gazebo>

  <joint name="${side}_wirst_j" type="revolute">
    <parent link="${side}_bottom_arm_link"/>
    <child link="${side}_wirst_l"/>
    <origin xyz="-${ARM_RADIUS} ${axis_y_signal*ARM_BOTTOM_LENGTH} 0"/>
    <axis xyz="1 0 0"/>
    <limit effort="1000.0" lower="-${PI/4}" upper="${PI/4}" velocity="0.5"/>
    <dynamics damping="50" friction="1"/>
  </joint>

<!-- PALM LINK -->
  <xacro:link_shape name="${side}_palm_l" color="White">
	<origin rpy="${PI/2} 0 0" xyz="0 ${axis_y_signal*0.17} 0 "/>
	<box size="${PALM_DEPTH} ${PALM_LENGTH} ${PALM_HEIGHT}"/>
  </xacro:link_shape>

  <gazebo reference="${side}_palm_l">
    <material>Gazebo/White</material>
  </gazebo>

  <joint name="${side}_upper_wirst_j" type="revolute">
    <parent link="${side}_wirst_l"/>
    <child link="${side}_palm_l"/>
    <origin xyz="0 ${axis_y_signal*0.10} 0"/>
    <axis xyz="0 0 1"/>
    <limit effort="1000.0" lower="-${PI/4}" upper="${PI/4}" velocity="0.5"/>
    <dynamics damping="50" friction="1"/>
  </joint>

<!--///	TRANSMICION ROS CONTROL	/// -->
   <xacro:transmission_block joint_name="${side}_wirst_j"/>
   <xacro:transmission_block joint_name="${side}_upper_wirst_j"/>

</xacro:macro>

<!--	///////		THUMB FINGER	///////	-->
<xacro:macro name="thumb_finger" params="side axis_y_signal lower upper ">
<!--	/////////////	-->
    <xacro:link_shape name="${side}_knuckle_bottom_thumb_l" color="Blue">
	<origin rpy="0 0 0" xyz="0 0 0"/>
	<sphere radius="${THUMB_RADIUS}" />
    </xacro:link_shape>

    <gazebo reference="${side}_knuckle_bottom_thumb_l">
      <material>Gazebo/Blue</material>
    </gazebo>

    <joint name="${side}_knuckle_bottom_thumb_j" type="revolute">
        <parent link="${side}_palm_l"/>
        <child link="${side}_knuckle_bottom_thumb_l"/>
        <origin xyz="0 ${axis_y_signal*THUMB_RADIUS} ${(PALM_LENGTH/2)+THUMB_RADIUS+TOLERANCE}" />
	<axis xyz="1 0 0"/>
	<limit effort="1000.0" lower="-${lower*(PI/2)}" upper="${upper*(PI/2)}" velocity="0.5"/> 		
	<dynamics damping="50" friction="1"/>
    </joint>

<!--	/////////////	-->
    <xacro:link_shape name="${side}_bottom_thumb_l" color="White">
	<origin rpy="0 0 0" xyz="0 0 ${THUMB_BOTTOM_LENGTH/2}"/>
	<cylinder radius="${THUMB_RADIUS}" length="${THUMB_BOTTOM_LENGTH}"/>
    </xacro:link_shape>

    <gazebo reference="${side}_bottom_thumb_l">
      <material>Gazebo/White</material>
    </gazebo>

    <joint name="${side}_knuckle_upper_thumb_j" type="revolute">
        <parent link="${side}_knuckle_bottom_thumb_l"/>
        <child link="${side}_bottom_thumb_l"/>
    	<origin xyz="0 0 0"/>
    	<axis xyz="0 1 0"/>
    	<limit effort="1000.0" lower="0" upper="${PI/2}" velocity="0.5"/>
    	<dynamics damping="50" friction="1"/>
    </joint>

<!--	///////////// -->
    <xacro:link_shape name="${side}_middle_thumb_l" color="White">
	<origin rpy="0 0 0" xyz="0 ${-1*axis_y_signal*THUMB_RADIUS} ${THUMB_TOP_LENGTH/2}"/>
	<cylinder radius="${THUMB_RADIUS}" length="${THUMB_TOP_LENGTH}"/>
    </xacro:link_shape>

    <gazebo reference="${side}_middle_thumb_l">
      <material>Gazebo/White</material>
    </gazebo>

    <joint name="${side}_middle_thumb_j" type="revolute">
        <parent link="${side}_bottom_thumb_l"/>
        <child link="${side}_middle_thumb_l"/>
    	<origin xyz="0 ${axis_y_signal*THUMB_RADIUS} ${THUMB_BOTTOM_LENGTH}"/> 
    	<axis xyz="1 0 0"/>
    	<limit effort="1000.0" lower="-${lower*(PI/2)}" upper="${upper*(PI/2)}" velocity="0.5"/>
    	<dynamics damping="50" friction="1"/>
    </joint>

<!--	/////////////	-->
    <xacro:link_shape name="${side}_top_thumb_l" color="White">
	<origin rpy="0 0 0" xyz="0 0 0"/>
	<sphere radius="${THUMB_RADIUS}"/>
    </xacro:link_shape>

    <gazebo reference="${side}_top_thumb_l">
      <material>Gazebo/White</material>
    </gazebo>

    <joint name="${side}_top_thumb_j" type="fixed">
        <parent link="${side}_middle_thumb_l"/>
        <child link="${side}_top_thumb_l"/>
    	<origin xyz="0 ${-1*axis_y_signal*0.06} 0.06"/>
    </joint>


<!--///	TRANSMICION ROS CONTROL	/// -->
   <xacro:transmission_block joint_name="${side}_knuckle_bottom_thumb_j"/>
   <xacro:transmission_block joint_name="${side}_knuckle_upper_thumb_j"/>
   <xacro:transmission_block joint_name="${side}_middle_thumb_j"/>

</xacro:macro>

<!--///////////////////	GENERIC FINGER	////////////////////////////////////////////
palm -> 0.43 for 4 fingers + 0.01 of interval between fingers 
	finger radius: 0.05
	0.05*2*4+3*0.01 = 0.43
///////////////////////////////////////////////////////////////////////////	-->

<xacro:macro name="generic_finger" 
	params="name side axis_y_signal lower upper ref_point bottom_length middle_length top_length">
<!--	///////////// -->	
    <xacro:link_shape name="${side}_knuckle_bottom_${name}_l" color="Blue">
	<origin rpy="0 0 0" xyz="0 0 0"/>
	<sphere radius="${GENERIC_FINGERS_RADIUS}" />
    </xacro:link_shape>

    <gazebo reference="${side}_knuckle_bottom_${name}_l">
      <material>Gazebo/Blue</material>
    </gazebo>
	
    <joint name="${side}_knuckle_bottom_${name}_j" type="revolute">
        <parent link="${side}_palm_l"/>
        <child link="${side}_knuckle_bottom_${name}_l"/>
        <origin xyz="${GENERIC_FINGERS_X} ${axis_y_signal*PALM_HEIGHT} ${ref_point}"/>
    	<axis xyz="0 0 1"/>
    	<limit effort="1000.0" lower="-${lower*(PI/2)}" upper="${upper*(PI/2)}" velocity="0.5"/>
    	<dynamics damping="50" friction="1"/>
    </joint>

<!--	/////////////	-->
    <xacro:link_shape name="${side}_bottom_${name}_l" color="White">
	<origin rpy="${PI/2} 0 0" xyz="0 ${axis_y_signal*(bottom_length/2)} 0"/>
	<cylinder radius="${GENERIC_FINGERS_RADIUS}" length="${bottom_length}"/>
    </xacro:link_shape>

    <gazebo reference="${side}_bottom_${name}_l">
      <material>Gazebo/White</material>
    </gazebo>

    <joint name="${side}_knuckle_upper_${name}_j" type="fixed">
        <parent link="${side}_knuckle_bottom_${name}_l"/>
        <child link="${side}_bottom_${name}_l"/>
    	<origin xyz="0 ${axis_y_signal*GENERIC_FINGERS_RADIUS} 0"/>
    </joint>

<!--	///////////// -->	
    <xacro:link_shape name="${side}_middle_${name}_l" color="White">
	<origin rpy="${PI/2} 0 0" xyz="-${GENERIC_FINGERS_RADIUS} ${axis_y_signal*middle_length/2} 0"/>
	<cylinder radius="${GENERIC_FINGERS_RADIUS}" length="${middle_length}"/>
    </xacro:link_shape>

    <gazebo reference="${side}_middle_${name}_l">
      <material>Gazebo/White</material>
    </gazebo>

    <joint name="${side}_middle_${name}_j" type="revolute">
        <parent link="${side}_bottom_${name}_l"/>
        <child link="${side}_middle_${name}_l"/>
    	<origin xyz="${GENERIC_FINGERS_RADIUS} ${axis_y_signal*bottom_length} 0"/>
    	<axis xyz="0 0 1"/>
    <limit effort="1000.0" lower="-${lower*(PI/2)}" upper="${upper*(PI/2)}" velocity="0.5"/>
    <dynamics damping="50" friction="1"/>
    </joint>

<!--	///////////// -->
    <xacro:link_shape name="${side}_top_${name}_l" color="White">
	<origin rpy="${PI/2} 0 0" xyz="-${GENERIC_FINGERS_RADIUS} ${axis_y_signal*(top_length/2)} 0"/>
	<cylinder radius="${GENERIC_FINGERS_RADIUS}" length="${top_length}"/>
    </xacro:link_shape>

    <gazebo reference="${side}_top_${name}_l">
      <material>Gazebo/White</material>
    </gazebo>

    <joint name="${side}_top_${name}_j" type="revolute">
        <parent link="${side}_middle_${name}_l"/>
        <child link="${side}_top_${name}_l"/>
    	<origin xyz="0 ${axis_y_signal*middle_length} 0"/>
    	<axis xyz="0 0 1"/>
   	<limit effort="1000.0" lower="-${lower*(PI/2)}" upper="${upper*(PI/2)}" velocity="0.5"/>
    	<dynamics damping="50" friction="1"/>
    </joint>

<!--	/////////////	 -->
    <xacro:link_shape name="${side}_toptop_${name}_l" color="White">
	<origin rpy="0 0 0" xyz="0 0 0"/>
	<sphere radius="${GENERIC_FINGERS_RADIUS}"/>
    </xacro:link_shape>

    <gazebo reference="${side}_toptop_${name}_l">
      <material>Gazebo/White</material>
    </gazebo>

    <joint name="${side}_toptop_${name}_j" type="fixed">
        <parent link="${side}_top_${name}_l"/>
        <child link="${side}_toptop_${name}_l"/>
    	<origin xyz="-${GENERIC_FINGERS_RADIUS} ${axis_y_signal*GENERIC_FINGERS_RADIUS} 0"/>
    </joint>

<!--///	TRANSMICION ROS CONTROL	/// -->
   <xacro:transmission_block joint_name="${side}_knuckle_bottom_${name}_j"/>
   <xacro:transmission_block joint_name="${side}_middle_${name}_j"/>
   <xacro:transmission_block joint_name="${side}_top_${name}_j"/>

</xacro:macro>

</robot>
