controller_list:
  - name: fake_torso_controller
    joints:
      []
  - name: fake_left_arm_controller
    joints:
      - l_shoulder_joint
      - l_top_arm_joint
      - l_elbow_joint
  - name: fake_right_arm_controller
    joints:
      - r_shoulder_joint
      - r_top_arm_joint
      - r_elbow_joint
  - name: fake_right_hand_controller
    joints:
      - r_wrist_joint
  - name: fake_left_hand_controller
    joints:
      - l_wrist_joint