controller_list:
  - name: "signbot/right/arm_controller"
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
     - r_shoulder_joint
     - r_top_arm_joint
     - r_elbow_joint

  - name: "signbot/right/hand/palm_controller"
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
     - r_wirst_j
     - r_upper_wirst_j

  - name: "signbot/right/hand/finger/thumb_controller"
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
     - r_knuckle_bottom_thumb_j
     - r_knuckle_upper_thumb_j
     - r_middle_thumb_j

  - name: "signbot/right/hand/finger/index_controller"
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
     - r_knuckle_bottom_index_j
     - r_middle_index_j
     - r_top_index_j

  - name: "signbot/right/hand/finger/middle_controller"
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
     - r_knuckle_bottom_middle_j
     - r_middle_middle_j
     - r_top_middle_j

  - name: "signbot/right/hand/finger/third_controller"
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
     - r_knuckle_bottom_third_j
     - r_middle_third_j
     - r_top_third_j

  - name: "signbot/right/hand/finger/little_controller"
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
     - r_knuckle_bottom_little_j
     - r_middle_little_j
     - r_top_little_j




  - name: "signbot/left/arm_controller"
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
     - l_shoulder_joint
     - l_top_arm_joint
     - l_elbow_joint

  - name: "signbot/left/hand/palm_controller"
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
     - l_wirst_j
     - l_upper_wirst_j

  - name: "signbot/left/hand/finger/thumb_controller"
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
     - l_knuckle_bottom_thumb_j
     - l_knuckle_upper_thumb_j
     - l_middle_thumb_j

  - name: "signbot/left/hand/finger/index_controller"
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
     - l_knuckle_bottom_index_j
     - l_middle_index_j
     - l_top_index_j

  - name: "signbot/left/hand/finger/middle_controller"
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
     - l_knuckle_bottom_middle_j
     - l_middle_middle_j
     - l_top_middle_j

  - name: "signbot/left/hand/finger/third_controller"
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
     - l_knuckle_bottom_third_j
     - l_middle_third_j
     - l_top_third_j

  - name: "signbot/left/hand/finger/little_controller"
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
     - l_knuckle_bottom_little_j
     - l_middle_little_j
     - l_top_little_j
