controller_list:
  - name: fake_base_controller
    joints:
      []
  - name: fake_torso_controller
    joints:
      []
  - name: fake_ritgh_arm_controller
    joints:
      - r_shoulder_joint
      - r_top_arm_joint
      - r_elbow_joint
  - name: fake_right_palm_controller
    joints:
      - r_wirst_j
      - r_upper_wirst_j
  - name: fake_r_thumb_f_controller
    joints:
      - r_knuckle_bottom_thumb_j
      - r_knuckle_upper_thumb_j
      - r_middle_thumb_j
  - name: fake_r_index_f_controller
    joints:
      - r_knuckle_bottom_index_j
      - r_middle_index_j
      - r_top_index_j
  - name: fake_r_middle_f_controller
    joints:
      - r_knuckle_bottom_middle_j
      - r_middle_middle_j
      - r_top_middle_j
  - name: fake_r_third_f_controller
    joints:
      - r_knuckle_bottom_third_j
      - r_middle_third_j
      - r_top_third_j
  - name: fake_r_little_f_controller
    joints:
      - r_knuckle_bottom_little_j
      - r_middle_little_j
      - r_top_little_j
  - name: fake_left_arm_controller
    joints:
      - l_shoulder_joint
      - l_top_arm_joint
      - l_elbow_joint
  - name: fake_left_palm_controller
    joints:
      - l_wirst_j
      - l_upper_wirst_j
  - name: fake_l_thumb_f_controller
    joints:
      - l_knuckle_bottom_thumb_j
      - l_knuckle_upper_thumb_j
      - l_middle_thumb_j
  - name: fake_l_index_f_controller
    joints:
      - l_knuckle_bottom_index_j
      - l_middle_index_j
      - l_top_index_j
  - name: fake_l_middle_f_controller
    joints:
      - l_knuckle_bottom_middle_j
      - l_middle_middle_j
      - l_top_middle_j
  - name: fake_l_third_f_controller
    joints:
      - l_knuckle_bottom_third_j
      - l_middle_third_j
      - l_top_third_j
  - name: fake_l_little_f_controller
    joints:
      - l_knuckle_bottom_little_j
      - l_middle_little_j
      - l_top_little_j